In [4]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [5]:
data = pd.read_csv('E:/Saint Peters/3rd Sem/DS - 600/Project/Data.csv')

In [6]:
data.head()

sex  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0    1   39        4.0              0         0.0     0.0                0   
1    0   46        2.0              0         0.0     0.0                0   
2    1   48        1.0              1        20.0     0.0                0   
3    0   61        3.0              1        30.0     0.0                0   
4    0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [7]:
data.isnull().sum()

sex                  0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [8]:
data = data.drop('education',axis=1)

In [9]:
data = data.dropna()

In [10]:
data.isnull().sum()

sex                0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [11]:
data.shape

(3749, 15)

In [12]:
X = data.drop('TenYearCHD', axis=1)
y = data['TenYearCHD']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [14]:
X = data.drop('TenYearCHD', axis=1)
y = data['TenYearCHD']

# Decision Tree Classifier

In [15]:
from sklearn.tree import DecisionTreeClassifier
decisiontreeclassifier_modal = DecisionTreeClassifier()
decisiontreeclassifier_modal.fit(X_train, y_train)

DecisionTreeClassifier()

In [16]:
y_pred_dt1 = decisiontreeclassifier_modal.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_dt1))
print(classification_report(y_test, y_pred_dt1))

[[796 168]
 [112  49]]
              precision    recall  f1-score   support

           0       0.88      0.83      0.85       964
           1       0.23      0.30      0.26       161

    accuracy                           0.75      1125
   macro avg       0.55      0.57      0.55      1125
weighted avg       0.78      0.75      0.77      1125



In [18]:
import joblib
joblib.dump(decisiontreeclassifier_modal, 'DecisionTreeClassifier.pkl')

['DecisionTreeClassifier.pkl']

# Random Forest Classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
randomforest_modal = RandomForestClassifier()
randomforest_modal.fit(X_train, y_train)

RandomForestClassifier()

In [21]:
y_pred_rf = randomforest_modal.predict(X_test)

In [22]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

[[956   8]
 [151  10]]
              precision    recall  f1-score   support

           0       0.86      0.99      0.92       964
           1       0.56      0.06      0.11       161

    accuracy                           0.86      1125
   macro avg       0.71      0.53      0.52      1125
weighted avg       0.82      0.86      0.81      1125



In [23]:
import joblib
joblib.dump(randomforest_modal, 'RandomForestClassifier.pkl')

['RandomForestClassifier.pkl']

# Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
logistic_modal = LogisticRegression()
logistic_modal.fit(X_train, y_train)

C:\Users\yashp\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
y_pred_logReg1 = logistic_modal.predict(X_test)

In [27]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_logReg1))
print(classification_report(y_test, y_pred_logReg1))

[[959   5]
 [154   7]]
              precision    recall  f1-score   support

           0       0.86      0.99      0.92       964
           1       0.58      0.04      0.08       161

    accuracy                           0.86      1125
   macro avg       0.72      0.52      0.50      1125
weighted avg       0.82      0.86      0.80      1125



In [28]:
import joblib
joblib.dump(logistic_modal, 'LogisticRegression.pkl')

['LogisticRegression.pkl']

In [29]:
from sklearn import metrics
#Models and their accuracy
print("******Models and their accuracy******")
print("Logistic Regression Classifier :: ", metrics.accuracy_score(y_test,y_pred_logReg1))
print("Decision Tree :: ", metrics.accuracy_score(y_test,y_pred_dt1))
print("Random Forest Classifier :: ", metrics.accuracy_score(y_test, y_pred_rf))

******Models and their accuracy******
Logistic Regression Classifier ::  0.8586666666666667
Decision Tree ::  0.7511111111111111
Random Forest Classifier ::  0.8586666666666667


In [32]:
#input_data = (1,39,0,0,0,0,0,0,195,106,70,26.97,80,77)
input_data = (0,67,1,30,0,0,1,0,112,150,95,28.58,65,103)

# changing input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = logistic_modal.predict(input_data_reshaped)
print(prediction)

print('Result', prediction[0])

[0]
Result 0


In [43]:
input_data = (0,61,1,30,0,0,1,0,295,150,60,28.58,65,103)

# changing input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

predictionmodal = joblib.load("LogisticRegression.pkl")

prediction_1 = predictionmodal.predict(input_data_reshaped)
print(prediction_1)

print('Result', prediction_1[0])

[1]
Result 1


In [44]:
input_data = (0,67,1,30,0,0,1,0,112,150,95,28.58,65,103)

# changing input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

predictionmodal = joblib.load("LogisticRegression.pkl")

prediction_1 = predictionmodal.predict(input_data_reshaped)
print(prediction_1)

print('Result', prediction_1[0])

[0]
Result 0
